---
markdown: kramdown

kramdown:
  input: GFM

title: ReviewNinja Documentation

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
  css_compressor: sass
  js_compressor:  uglifier
  cache:          true


exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
  - README.md
