source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'jekyll'
gem 'jekyll-assets'
gem 'rake'
gem 'kramdown'
gem 'breakpoint', '~> 1.x'
gem 'respond-to'
gem 'rubyzip'
gem 'sass'
gem 'uglifier', '>= 2.7.1'
gem 'bootstrap-sass', '>= 3.3.4.1'
gem 'font-awesome-sass'
gem 'webrick'

