source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'jekyll', '>= 3.6.3'
gem 'jekyll-assets', '>= 1.0.0'
gem 'rake'
gem 'kramdown'
gem 'breakpoint', '~> 1.x'
gem 'respond-to'
gem 'rubyzip'
gem 'sass'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'webrick'

